Feat/make website
ems-project/EMSMakerBundle pull request #14
Opened 2021-01-18 16:53 UTC by theus77

|Q              |A  |
|---------------|---|
|Bug fix?       |Y|
|New feature?   |Y|	
|BC breaks?     |N|	
|Deprecations?  |N|	
|Fixed tickets  |N|	

Make a demo website from scratch

2021-01-18 21:12 UTC, Davidmattei requested changes

2021-01-18 21:12 UTC, Davidmattei commented on Command/RevisionCommand.php
> +    private function resolveRevision(array $config)
```suggestion
    private function resolveRevision(array $config): array
```

2021-01-18 21:12 UTC, Davidmattei commented on Command/AnalyzerCommand.php
> +    public function makeAnalyzers(array $analyzers): void
can be private?

2021-01-18 21:43 UTC, theus77 commented on Command/AnalyzerCommand.php
> +    public function makeAnalyzers(array $analyzers): void
No, used by the demo command

2021-01-19 08:42 UTC, Davidmattei submitted a review, later dismissed

2021-01-20 17:55 UTC, merged